from cherrypicker import CherryPicker
import json
import pandas as pd

# This file converts .json files under data/json to .csv files to be stored in data/csv.
# Conversion method: .json -> pandas DataFrame object -> .csv

json_dir = "/home/mertbarut/42/persevere/data/json/"
csv_dir = "/home/mertbarut/42/persevere/data/csv/"

# Handle all .json -> dataframe conversion
achievements = pd.read_json(json_dir + 'achievements.json')
achievements_users_330 = pd.read_json(json_dir + 'achievements_users_330.json')
achievements_users_331 = pd.read_json(json_dir + 'achievements_users_331.json')
achievements_users_332 = pd.read_json(json_dir + 'achievements_users_332.json')
achievements_users_333 = pd.read_json(json_dir + 'achievements_users_333.json')
achievements_users_334 = pd.read_json(json_dir + 'achievements_users_334.json')
achievements_users_335 = pd.read_json(json_dir + 'achievements_users_335.json')
achievements_users_336 = pd.read_json(json_dir + 'achievements_users_336.json')
achievements_users_337 = pd.read_json(json_dir + 'achievements_users_337.json')
achievements_users_338 = pd.read_json(json_dir + 'achievements_users_338.json')
achievements_users_339 = pd.read_json(json_dir + 'achievements_users_339.json')
achievements_users_340 = pd.read_json(json_dir + 'achievements_users_340.json')
achievements_users_341 = pd.read_json(json_dir + 'achievements_users_341.json')
achievements_users_342 = pd.read_json(json_dir + 'achievements_users_342.json')
achievements_users_343 = pd.read_json(json_dir + 'achievements_users_343.json')
achievements_users_344 = pd.read_json(json_dir + 'achievements_users_344.json')
achievements_users_345 = pd.read_json(json_dir + 'achievements_users_345.json')
achievements_users_347 = pd.read_json(json_dir + 'achievements_users_347.json')
achievements_users_348 = pd.read_json(json_dir + 'achievements_users_348.json')
achievements_users_353 = pd.read_json(json_dir + 'achievements_users_353.json')
achievements_users_354 = pd.read_json(json_dir + 'achievements_users_354.json')
achievements_users_355 = pd.read_json(json_dir + 'achievements_users_355.json')
achievements_users_356 = pd.read_json(json_dir + 'achievements_users_356.json')
achievements_users_357 = pd.read_json(json_dir + 'achievements_users_357.json')
achievements_users_358 = pd.read_json(json_dir + 'achievements_users_358.json')
achievements_users_359 = pd.read_json(json_dir + 'achievements_users_359.json')
achievements_users_360 = pd.read_json(json_dir + 'achievements_users_360.json')
achievements_users_361 = pd.read_json(json_dir + 'achievements_users_361.json')
achievements_users_362 = pd.read_json(json_dir + 'achievements_users_362.json')
achievements_users_363 = pd.read_json(json_dir + 'achievements_users_363.json')
achievements_users_364 = pd.read_json(json_dir + 'achievements_users_364.json')
achievements_users_365 = pd.read_json(json_dir + 'achievements_users_365.json')
achievements_users_366 = pd.read_json(json_dir + 'achievements_users_366.json')
achievements_users_367 = pd.read_json(json_dir + 'achievements_users_367.json')
achievements_users_368 = pd.read_json(json_dir + 'achievements_users_368.json')
achievements_users_369 = pd.read_json(json_dir + 'achievements_users_369.json')
# achievements_users_370 = pd.read_json(json_dir + 'achievements_users_370.json')
# achievements_users_371 = pd.read_json(json_dir + 'achievements_users_371.json')
# achievements_users_372 = pd.read_json(json_dir + 'achievements_users_372.json')
# achievements_users_373 = pd.read_json(json_dir + 'achievements_users_373.json')
achievements_users_374 = pd.read_json(json_dir + 'achievements_users_374.json')
achievements_users_375 = pd.read_json(json_dir + 'achievements_users_375.json')
achievements_users_376 = pd.read_json(json_dir + 'achievements_users_376.json')
achievements_users_438 = pd.read_json(json_dir + 'achievements_users_438.json')

# Handle all dataframe -> .csv conversion
achievements.to_csv(csv_dir + 'achievements.csv')
achievements_users_330.to_csv(csv_dir + 'achievements_users_330.csv')
achievements_users_331.to_csv(csv_dir + 'achievements_users_331.csv')
achievements_users_332.to_csv(csv_dir + 'achievements_users_332.csv')
achievements_users_333.to_csv(csv_dir + 'achievements_users_333.csv')
achievements_users_334.to_csv(csv_dir + 'achievements_users_334.csv')
achievements_users_335.to_csv(csv_dir + 'achievements_users_335.csv')
achievements_users_336.to_csv(csv_dir + 'achievements_users_336.csv')
achievements_users_337.to_csv(csv_dir + 'achievements_users_337.csv')
achievements_users_338.to_csv(csv_dir + 'achievements_users_338.csv')
achievements_users_339.to_csv(csv_dir + 'achievements_users_339.csv')
achievements_users_340.to_csv(csv_dir + 'achievements_users_340.csv')
achievements_users_341.to_csv(csv_dir + 'achievements_users_341.csv')
achievements_users_342.to_csv(csv_dir + 'achievements_users_342.csv')
achievements_users_343.to_csv(csv_dir + 'achievements_users_343.csv')
achievements_users_344.to_csv(csv_dir + 'achievements_users_344.csv')
achievements_users_345.to_csv(csv_dir + 'achievements_users_345.csv')
achievements_users_347.to_csv(csv_dir + 'achievements_users_347.csv')
achievements_users_348.to_csv(csv_dir + 'achievements_users_348.csv')
achievements_users_353.to_csv(csv_dir + 'achievements_users_353.csv')
achievements_users_354.to_csv(csv_dir + 'achievements_users_354.csv')
achievements_users_355.to_csv(csv_dir + 'achievements_users_355.csv')
achievements_users_356.to_csv(csv_dir + 'achievements_users_356.csv')
achievements_users_357.to_csv(csv_dir + 'achievements_users_357.csv')
achievements_users_358.to_csv(csv_dir + 'achievements_users_358.csv')
achievements_users_359.to_csv(csv_dir + 'achievements_users_359.csv')
achievements_users_360.to_csv(csv_dir + 'achievements_users_360.csv')
achievements_users_361.to_csv(csv_dir + 'achievements_users_361.csv')
achievements_users_362.to_csv(csv_dir + 'achievements_users_362.csv')
achievements_users_363.to_csv(csv_dir + 'achievements_users_363.csv')
achievements_users_364.to_csv(csv_dir + 'achievements_users_364.csv')
achievements_users_365.to_csv(csv_dir + 'achievements_users_365.csv')
achievements_users_366.to_csv(csv_dir + 'achievements_users_366.csv')
achievements_users_367.to_csv(csv_dir + 'achievements_users_367.csv')
achievements_users_368.to_csv(csv_dir + 'achievements_users_368.csv')
achievements_users_369.to_csv(csv_dir + 'achievements_users_369.csv')
# achievements_users_370.to_csv(csv_dir + 'achievements_users_370.csv')
# achievements_users_371.to_csv(csv_dir + 'achievements_users_371.csv')
# achievements_users_372.to_csv(csv_dir + 'achievements_users_372.csv')
# achievements_users_373.to_csv(csv_dir + 'achievements_users_373.csv')
achievements_users_374.to_csv(csv_dir + 'achievements_users_374.csv')
achievements_users_375.to_csv(csv_dir + 'achievements_users_375.csv')
achievements_users_376.to_csv(csv_dir + 'achievements_users_376.csv')
achievements_users_438.to_csv(csv_dir + 'achievements_users_438.csv')
